# Generated by Django 2.2.17 on 2021-04-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluArt', '0002_auto_20210331_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='content',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('abstract', 'Abstract'), ('animals', 'Animals'), ('anime/cartoons', 'Anime/Cartoons'), ('futuristic', 'Futuristic'), ('surrealism', 'Surrealism'), ('pixel art', 'Pixel Art'), ('nature', 'Nature')], default='Abstract', max_length=25),
        ),
    ]
