# Generated by Django 2.2.17 on 2021-03-24 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluArt', '0002_artwork_category_comments_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('content', models.CharField(max_length=800)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluArt.UserProfile')),
            ],
        ),
        migrations.AlterField(
            model_name='comments',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluArt.Post'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluArt.Post'),
        ),
        migrations.DeleteModel(
            name='Artwork',
        ),
    ]
