# Generated by Django 2.2.17 on 2021-04-02 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluArt', '0002_auto_20210331_1334'),
        ('evaluArt', '0003_auto_20210401_1221'),
    ]

    operations = [
    ]
