# Generated by Django 2.2.17 on 2021-03-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluArt', '0004_auto_20210325_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='category',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience',
            field=models.CharField(choices=[('0', 'Beginner'), ('1', 'Novice'), ('2', 'expert'), ('3', 'professional')], default='1', max_length=12),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='picture',
            field=models.ImageField(blank=True, upload_to='user/%Y/%m/%d/'),
        ),
    ]
