# Generated by Django 2.2.17 on 2021-04-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluArt', '0004_merge_20210402_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='picture',
            field=models.ImageField(blank=True, default='default/default.jpg', upload_to='user/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
