# Generated by Django 2.2.17 on 2021-04-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluArt', '0005_auto_20210402_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
