# Generated by Django 2.2.17 on 2021-04-03 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluArt', '0006_auto_20210402_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='number',
            field=models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
