# Generated by Django 2.2.17 on 2021-04-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluArt', '0009_auto_20210403_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='rating_average',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
