# Generated by Django 2.2.17 on 2021-04-03 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluArt', '0011_auto_20210403_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='rating_average',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='rating_count',
        ),
    ]
