# Generated by Django 2.2.17 on 2021-04-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluArt', '0014_auto_20210403_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='number',
            field=models.IntegerField(choices=[('1', '1 - Hated It'), ('2', '2 - Mediocre'), ('3', '3 - Good'), ('4', '4 - Great'), ('5', '5 - Masterpiece')]),
        ),
    ]
